# Generated by Django 4.2.5 on 2023-10-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panificacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productopan',
            new_name='panificacion',
        ),
        migrations.RenameModel(
            old_name='pan',
            new_name='tiposdepan',
        ),
        migrations.AlterModelOptions(
            name='tiposdepan',
            options={'verbose_name': 'tipos de pan', 'verbose_name_plural': 'tipos de panes'},
        ),
    ]
