# Generated by Django 4.2.5 on 2023-10-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panificacion', '0002_rename_productopan_panificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposdepan',
            name='tamaño',
        ),
    ]
