# Generated by Django 4.2.5 on 2023-09-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Nacimiento', models.DateField(null=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('paciente', models.CharField(max_length=100)),
            ],
        ),
    ]
