# Generated by Django 4.2.5 on 2023-10-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postres', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tiposdepostre',
            new_name='tipodepostre',
        ),
    ]
