# Generated by Django 4.2.5 on 2023-10-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postres', '0002_rename_tiposdepostre_tipodepostre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodepostre',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='postre',
        ),
        migrations.DeleteModel(
            name='tipodepostre',
        ),
    ]
